### PR TITLE
Refactored 'MarkerIcon' to use 'getMarker'. Issue #44

### PR DESCRIPTION
**Pull request by thorn573**
Added method 'getMarker' to reduce amount of 'var marker' and 'MarkerIcon' thus reducing instabillity.

Tested successfully with Chrome and Firefox.

### CODE REVIEW

**Comment by cmcfadden** [comment]
I don't think this is quite right. You're not keeping track of all the markers that get created anymore. The old code stored each marker in an array (this.markers[i] = marker;).  The reason things kind of look like they're working right now is that as soon as you do the L.Marker, Leaflet adds them to the map. But you're not actually tracking their state internally anymore, so I suspect dragging and clicking won't work right or consistently? 

Defining a function inline like this is also probably not a pattern we want, since it confuses scope - you're counting on draggable, marker, etc being in scope. Instead, I'd probably define it as a standalone function (look at the MarkerIcon function as an example) and just pass in the Lt.basepath and 'draggable'. 

In the end the function might look more like:
```
function getMarker(icon, path, latLng, title, draggable) {
return L.marker(latLng, {
              icon: new MarkerIcon(icon, path),
              draggable: draggable,
              title: title,
              riseOnHover: true
            });
}
```

**Comment by cmcfadden** [comment]
Also, you don't need/want the `new` keyword when just calling a function. New is used to instantiate a copy of an object (which also calls its constructor if it has one).

**Comment by thorn573** [comment]
Dragging & clicking work consistently (tested by 'Save a local copy' test and just playing around with it). 

I'll change where the function lives. However, since we know latlng, draggable, rise on hover, and path are constants, do they need their own function variable/input?

**Comment by cmcfadden** [comment]
The idea with a function is to make it self contained. It should be obvious to someone looking at it where the values it uses come from, and where the data it touches goes. Right now, that data is sort of leaking because in this particularly setup, those variables have become globally available to the function. That's more a bug than a feature though - it means if someone got changed outside the function (renaming draggable, or rearranging the code) the function might suddenly stop working, and it wouldn't be clear why.

As a design principle, a function like this should take some input, and return some output, and not alter the state of anything else outside the function.

**Comment by cmcfadden** [comment]
also, if draggable is really going to always be true, you can leave that off (and remove the variable) and just set it to true.

**Comment by thorn573** [comment]
Its true in popout mode but not browser mode. So the set up it to change its state (false -> true) when window includes 'popout'.

**Comment by thorn573** [comment]
How come it works then? JS foolery?

Trying to work it out in my head.

**Comment by cmcfadden** [comment]
Because right now you're still altering the global scope "marker" variable, which is defined a little further up.

**Comment by cmcfadden** [comment]
looks good

**Pull request merged**
